conda-forge/phono3py-feedstock

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_numpy1.16python3.6.____cpython.yaml, .ci_support/linux_64_numpy1.16python3.7.____cpython.yaml, .ci_support/linux_64_numpy1.16python3.8.____cpython.yaml, .ci_support/linux_64_numpy1.19python3.9.____cpython.yaml, .ci_support/osx_64_numpy1.16python3.6.____cpython.yaml, .ci_support/osx_64_numpy1.16python3.7.____cpython.yaml, .ci_support/osx_64_numpy1.16python3.8.____cpython.yaml, .ci_support/osx_64_numpy1.19python3.9.____cpython.yaml, .scripts/run_docker_build.sh, recipe/meta.yaml
=> Manual update to 1.22.0

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_numpy1.16python3.6.____cpython.yaml, .ci_support/linux_64_numpy1.16python3.7.____cpython.yaml, .ci_support/linux_64_numpy1.16python3.8.____cpython.yaml, .ci_support/linux_64_numpy1.19python3.9.____cpython.yaml, .ci_support/osx_64_numpy1.16python3.6.____cpython.yaml, .ci_support/osx_64_numpy1.16python3.7.____cpython.yaml, .ci_support/osx_64_numpy1.16python3.8.____cpython.yaml, .ci_support/osx_64_numpy1.19python3.9.____cpython.yaml, .scripts/run_docker_build.sh, recipe/meta.yaml
=> Manual update to 1.22.1

recipe/meta.yaml
=> Use pypi version again

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .ci_support/linux_64_python3.10.____cpython.yaml, .ci_support/linux_64_python3.7.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/osx_64_python3.10.____cpython.yaml, .ci_support/osx_64_python3.7.____cpython.yaml, .ci_support/osx_64_python3.8.____cpython.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .scripts/run_osx_build.sh, README.md, recipe/meta.yaml
Checklist
This PR is for 
* Replacing MKL by openblas
* `extra_link_args = -lgomp` is added to `site.cfg` for `[linux]`
* Run test to check compiled phono3py
* Avoid running test for `[osx]` with py37 because the test fails
=> meta.yaml with openblas instead of MKL

recipe/meta.yaml
Phono3py build system was modified to avoid relying on numpy.distutils that is deprecated.
Checklist
=> Update recipe for v2.4

.ci_support/linux_64_numpy1.20python3.8.____cpython.yaml, .ci_support/linux_64_numpy1.20python3.9.____cpython.yaml, .ci_support/linux_64_numpy1.21python3.10.____cpython.yaml, .ci_support/linux_64_numpy1.23python3.11.____cpython.yaml, recipe/meta.yaml
Checklist
@conda-forge-admin please rerender
=> Release v2.5.0

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .ci_support/linux_64_numpy1.21python3.8.____cpython.yaml, .ci_support/linux_64_numpy1.21python3.9.____cpython.yaml, .ci_support/osx_64_numpy1.21python3.8.____cpython.yaml, .ci_support/osx_64_numpy1.21python3.9.____cpython.yaml, .ci_support/osx_arm64_numpy1.21python3.8.____cpython.yaml, .ci_support/osx_arm64_numpy1.21python3.9.____cpython.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, README.md, recipe/meta.yaml
=> Update phonopy version dependency for next minor version update

recipe/meta.yaml
Checklist
The test should fail. Then, I will release new version of phono3py, which should pass the test.
=> Increment phonopy version dependency

recipe/meta.yaml
=> Limit spglib version < 2.4.0

recipe/meta.yaml
Checklist
Update phonopy version dependency for the next phono3py release.
=> Update phonopy version dependency

recipe/meta.yaml
=> Remove spglib version limitation

recipe/meta.yaml
Checklist
Dependency of phonopy version was updated for the next release of phonop3y.
=> Update phonopy depencency

.ci_support/linux_64_numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_numpy1.22python3.8.____cpython.yaml, .ci_support/linux_64_numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_numpy1.23python3.11.____cpython.yaml, .ci_support/linux_64_numpy1.26python3.12.____cpython.yaml, .ci_support/osx_64_numpy1.22python3.10.____cpython.yaml, .ci_support/osx_64_numpy1.22python3.8.____cpython.yaml, .ci_support/osx_64_numpy1.22python3.9.____cpython.yaml, .ci_support/osx_64_numpy1.23python3.11.____cpython.yaml, .ci_support/osx_64_numpy1.26python3.12.____cpython.yaml, .ci_support/osx_arm64_numpy1.22python3.10.____cpython.yaml, .ci_support/osx_arm64_numpy1.22python3.8.____cpython.yaml, .ci_support/osx_arm64_numpy1.22python3.9.____cpython.yaml, .ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml, .ci_support/osx_arm64_numpy1.26python3.12.____cpython.yaml, recipe/meta.yaml
=> Update for new build system of phono3py

.ci_support/linux_64_numpy1.22python3.8.____cpython.yaml, .ci_support/linux_64_numpy2.0python3.10.____cpython.yaml, .ci_support/linux_64_numpy2.0python3.11.____cpython.yaml, .ci_support/linux_64_numpy2.0python3.12.____cpython.yaml, .ci_support/linux_64_numpy2.0python3.9.____cpython.yaml, .ci_support/osx_64_numpy1.22python3.8.____cpython.yaml, .ci_support/osx_64_numpy2.0python3.10.____cpython.yaml, .ci_support/osx_64_numpy2.0python3.11.____cpython.yaml, .ci_support/osx_64_numpy2.0python3.12.____cpython.yaml, .ci_support/osx_64_numpy2.0python3.9.____cpython.yaml, .ci_support/osx_arm64_numpy1.22python3.8.____cpython.yaml, .ci_support/osx_arm64_numpy2.0python3.10.____cpython.yaml, .ci_support/osx_arm64_numpy2.0python3.11.____cpython.yaml, .ci_support/osx_arm64_numpy2.0python3.12.____cpython.yaml, .ci_support/osx_arm64_numpy2.0python3.9.____cpython.yaml, recipe/meta.yaml
=> Update for v3.4

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_numpy2.0python3.10.____cpython.yaml, .ci_support/linux_64_numpy2.0python3.11.____cpython.yaml, .ci_support/linux_64_numpy2.0python3.12.____cpython.yaml, .ci_support/linux_64_numpy2.0python3.9.____cpython.yaml, .ci_support/linux_64_numpy2python3.13.____cp313.yaml, .ci_support/osx_64_numpy2.0python3.10.____cpython.yaml, .ci_support/osx_64_numpy2.0python3.11.____cpython.yaml, .ci_support/osx_64_numpy2.0python3.12.____cpython.yaml, .ci_support/osx_64_numpy2.0python3.9.____cpython.yaml, .ci_support/osx_64_numpy2python3.13.____cp313.yaml, .ci_support/osx_arm64_numpy2.0python3.10.____cpython.yaml, .ci_support/osx_arm64_numpy2.0python3.11.____cpython.yaml, .ci_support/osx_arm64_numpy2.0python3.12.____cpython.yaml, .ci_support/osx_arm64_numpy2.0python3.9.____cpython.yaml, .ci_support/osx_arm64_numpy2python3.13.____cp313.yaml, build-locally.py, recipe/meta.yaml
=> Release v3.8.0

.scripts/run_osx_build.sh, recipe/meta.yaml
=> Release v3.9.0

recipe/meta.yaml
=> Release v3.10.0

recipe/meta.yaml
=> Release v3.11.0

.gitignore, recipe/meta.yaml
=> Release v3.12.1

recipe/meta.yaml
=> Release v3.13.0

recipe/meta.yaml
=> Release v3.14.0

recipe/meta.yaml
Checklist
Similar to https://github.com/conda-forge/phonopy-feedstock/pull/203
=> Tentative fix windows commands

.scripts/run_docker_build.sh, build-locally.py, recipe/meta.yaml
=> Release v3.15.1

.ci_support/win_64_python3.10.____cpython.yaml, .ci_support/win_64_python3.11.____cpython.yaml, .ci_support/win_64_python3.12.____cpython.yaml, .ci_support/win_64_python3.13.____cp313.yaml, .ci_support/win_64_python3.9.____cpython.yaml, build-locally.py, recipe/meta.yaml
Checklist
@conda-forge-admin, please rerende
=> Release v3.17.0

recipe/meta.yaml
=> Release v3.19.0

recipe/meta.yaml
=> Release v3.19.1
